services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    network_mode: "host"
    environment:
      MYSQL_DATABASE: billing_rtnet
      MYSQL_USER: rtnet
      MYSQL_PASSWORD: rtnet123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    restart: unless-stopped
    network_mode: "host"
    environment:
      DB_HOST: 127.0.0.1
      DB_NAME: billing_rtnet
      DB_USER: rtnet
      DB_PASS: rtnet123
    volumes:
      - ./app:/var/www/html

  adminer:
    image: adminer:latest
    restart: unless-stopped
    network_mode: "host"

volumes:
  db_data: